@GameServer_HostAddress = https://localhost:7263

GET {{GameServer_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{GameServer_HostAddress}}/createGame
Content-Type: application/json

{
  //CreateGameRequest
}

###
